name: Resume CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image with tag
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.run_number }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
    - name: Tag the Docker image with tag
      run: docker tag my-image-name:${{ github.run_number }} ${ secrets.REGISTRY_USERNAME }/my-image-name:${{ github.run_number }}
    - name: Push the Docker image with tag
      run: docker push ${ secrets.REGISTRY_USERNAME }/my-image-name:${{ github.run_number }}
